### ISSUE TITLE
I can't share my contributions in private repo to everybody

### ISSUE THREAD

**Issue by yuyakeFuture** [yuyakeFuture/Samples#2]
I can't share my contributions in private repo to everybody.
Who can help me?

**Comment by SeasonedSoftDev** [comment]
Please check your git config:
first: Email address is correct?
Second: Username is conrrect?

**Comment by SeasonedSoftDev** [comment]
You can check using those commands:
git config --list (To check all information set now)

If not matched
git config --list user.email "your email addr"
git config --list user.name "your account name"

Try commit and push

You'll find the problem solved.
